### ISSUE TITLE
Migration from Travis org to com

### ISSUE THREAD

**Issue by ArchiFleKs** [go-semantic-release/semantic-release#16]
Travis is migrating open source repo to travis.com. When I tried to deploy a new public repository on travis.com I get this error:

```
[semantic-release]: running CI condition...
[semantic-release]: GET https://api.travis-ci.org/builds/96825862: 404 
```

Is there any way to tell semantic release to use travis.com ?

**Comment by christophwitzko** [comment]
Hi @ArchiFleKs, 

currently, semantic-release uses the `api.travis-ci.com` endpoint only if the GitHub repo is private. This sadly won't work anymore, after Travis CI has announced to unify their infrastructure.

I couldn't find a straight forward solution to determine which endpoint semantic-release should use, because you cannot really tell if an open source repo is already using the new `.com` endpoint.

I will try to dig deeper into this in the next few days, and if you might have a solution I am happy to hear about it. 😊

Cheers,
Christoph

**Comment by ArchiFleKs** [comment]
Hi @christophwitzko,

Thank you for your answer.
Maybe in addition of autodetection, just adding an optional flag to choose between org and com might be a solution.

**Comment by christophwitzko** [comment]
Thanks @ArchiFleKs, that sounds like a good solution for now. I will add a `--travis-com` flag.

**Comment by christophwitzko** [comment]
Hi, I just release version `1.11.0`. Can you try to use this version on your travis build?
If you are using curl to install you can just use this line:
`curl -SL https://get-release.xyz/go-semantic-release/semantic-release/linux/amd64/1.11.x -o ~/semantic-release && chmod +x ~/semantic-release`

**Comment by ArchiFleKs** [comment]
Seems to work for me with --travis-com, thanks a lot.

**Comment by christophwitzko** [comment]
@ArchiFleKs awesome and thanks for your support.
