### ISSUE TITLE
Question: do we really need a Gitlab personal access token for Gitlab ci?

### ISSUE THREAD

**Issue by xNok** [go-semantic-release/semantic-release#169]
I am currious to understand why this is a requirement for Gitlab because I used the built in [gitlab ci release](https://docs.gitlab.com/ee/user/project/releases/release_cicd_examples.html#create-release-metadata-in-a-custom-script) tooling and it doesn't need a token to create a release.

Based on their code they use the `CI_JOB_TOKEN` instead: https://gitlab.com/gitlab-org/release-cli

I am not familiar with the inner working of the project yet so I was wondering if this was still a requirement. The `CI_JOB_TOKEN` is a recent addition so I can imagine that maybe it could works as well.

**Comment by cliedeman** [comment]
Hi @xNok 

Looks like the docs are a little outdated.
https://github.com/go-semantic-release/semantic-release/issues/141

You don't need to provide a PAT but there are some restrictions, The only one I can recall off the top of my head is that we required the `GIT_STRATEGY` to be clone so that we can access the commits without the API.

**Comment by dannylongeuay** [comment]
Docs have been updated with an example of using the job token
