### ISSUE TITLE
The initial run of semantic-release automatically increments the MAJOR version

### ISSUE THREAD

**Issue by brooksjbr** [go-semantic-release/semantic-release#19]
I'm experiencing something unexpected on the initial run of semantic-release. The MAJOR version is incremented, but a "BREAKING CHANGES" commit hasn't been made.

There have been a number of `feat` commit messages pushed, with the expectation of the MINOR version incrementing.  

For example, if the tagged version is currently v0.0.0 and a commit is pushed `feat(app): new feature` I expect the updated version to be v0.1.0, but I'm seeing v1.0.0

**Comment by christophwitzko** [comment]
Hi @brooksjbr, semantic-release does not support versions for [initial development](https://semver.org/#spec-item-4).

**Comment by xoxys** [comment]
Hello @christophwitzko is this still true? Because in this case the example from https://github.com/go-semantic-release/commit-analyzer-cz#bump-minor-version-012---020 seems to be wrong, indicating that bumping minor versions of `0.x.y` is supported. I also encountered this problem when I expected a minor version bump from a `0.x.y` version, since there were no breaking changes.

**Comment by xoxys** [comment]
Ah I missed that flag. Thanks!
